import { jsPDF } from 'jspdf'

/**
 * NoteExporter - Export notes in multiple formats
 */
export const NoteExporter = {
  /**
   * Export note as Markdown file
   * @param {Object} note - Note object with content and tags
   * @param {string} docTitle - Document title for header
   * @returns {Blob} Markdown file blob
   */
  exportAsMarkdown(note, docTitle) {
    const header = `# Notes: ${docTitle}\n\n`
    const tags = note.tags?.length
      ? `**Tags:** ${note.tags.join(', ')}\n\n---\n\n`
      : ''
    const content = header + tags + (note.content || '')
    return new Blob([content], { type: 'text/markdown;charset=utf-8' })
  },

  /**
   * Export note as plain text file
   * @param {Object} note - Note object with content and tags
   * @param {string} docTitle - Document title for header
   * @returns {Blob} Plain text file blob
   */
  exportAsText(note, docTitle) {
    const header = `Notes: ${docTitle}\n${'='.repeat(40)}\n\n`
    const tags = note.tags?.length
      ? `Tags: ${note.tags.join(', ')}\n\n---\n\n`
      : ''
    const content = header + tags + (note.content || '')
    return new Blob([content], { type: 'text/plain;charset=utf-8' })
  },

  /**
   * Export note as PDF file
   * @param {Object} note - Note object with content and tags
   * @param {string} docTitle - Document title for header
   * @returns {Blob} PDF file blob
   */
  exportAsPDF(note, docTitle) {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    })

    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 20
    const maxWidth = pageWidth - margin * 2
    let yPos = margin

    // Title
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(16)
    const titleLines = doc.splitTextToSize(`Notes: ${docTitle}`, maxWidth)
    doc.text(titleLines, margin, yPos)
    yPos += titleLines.length * 8 + 5

    // Tags
    if (note.tags?.length) {
      doc.setFont('helvetica', 'italic')
      doc.setFontSize(10)
      doc.setTextColor(100)
      doc.text(`Tags: ${note.tags.join(', ')}`, margin, yPos)
      yPos += 8
      doc.setTextColor(0)
    }

    // Horizontal line
    doc.setDrawColor(200)
    doc.line(margin, yPos, pageWidth - margin, yPos)
    yPos += 8

    // Content
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    const contentLines = doc.splitTextToSize(note.content || 'No notes yet.', maxWidth)

    for (const line of contentLines) {
      if (yPos > 280) {
        doc.addPage()
        yPos = margin
      }
      doc.text(line, margin, yPos)
      yPos += 6
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages()
    doc.setFontSize(9)
    doc.setTextColor(150)
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.text(
        `Generated by ScholarLib - Page ${i} of ${pageCount}`,
        pageWidth / 2,
        290,
        { align: 'center' }
      )
    }

    return doc.output('blob')
  },

  /**
   * Export note as DOCX file
   * Uses simple XML structure for Word compatibility
   * @param {Object} note - Note object with content and tags
   * @param {string} docTitle - Document title for header
   * @returns {Blob} DOCX file blob
   */
  exportAsDOCX(note, docTitle) {
    // Simple Word XML format (Office Open XML)
    const escapeXml = (text) => {
      return (text || '').replace(/[<>&'"]/g, (c) => ({
        '<': '&lt;',
        '>': '&gt;',
        '&': '&amp;',
        "'": '&apos;',
        '"': '&quot;'
      })[c])
    }

    const content = note.content || ''
    const paragraphs = content.split('\n').map(p =>
      `<w:p><w:r><w:t>${escapeXml(p)}</w:t></w:r></w:p>`
    ).join('')

    const tags = note.tags?.length
      ? `<w:p><w:pPr><w:pStyle w:val="Subtitle"/></w:pPr><w:r><w:rPr><w:i/></w:rPr><w:t>Tags: ${escapeXml(note.tags.join(', '))}</w:t></w:r></w:p>`
      : ''

    const xml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p>
      <w:pPr><w:pStyle w:val="Title"/></w:pPr>
      <w:r><w:t>Notes: ${escapeXml(docTitle)}</w:t></w:r>
    </w:p>
    ${tags}
    <w:p><w:r><w:t></w:t></w:r></w:p>
    ${paragraphs}
  </w:body>
</w:document>`

    // Note: This creates a minimal DOCX. For better compatibility,
    // we'd need to create a proper ZIP with content types and relationships.
    // For now, we return a simple XML that Word can open.
    return new Blob([xml], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' })
  },

  /**
   * Copy note content to clipboard
   * @param {Object} note - Note object with content
   * @param {string} docTitle - Document title for header
   * @returns {Promise<void>}
   */
  async copyToClipboard(note, docTitle) {
    const header = `# Notes: ${docTitle}\n\n`
    const tags = note.tags?.length
      ? `**Tags:** ${note.tags.join(', ')}\n\n---\n\n`
      : ''
    const content = header + tags + (note.content || '')

    await navigator.clipboard.writeText(content)
  },

  /**
   * Trigger file download
   * @param {Blob} blob - File blob
   * @param {string} filename - Download filename
   */
  downloadFile(blob, filename) {
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }
}
