import { PageStore } from '../PageStore'
import { WikiPaths } from '../WikiPaths'
import { readJSONOrNull, writeJSONWithRevision } from '../WikiStorage'
import { ObsidianFormatter } from './ObsidianFormatter'

function displayType(type) {
  return String(type || 'page').replace(/_/g, ' ')
}

async function writeText(adapter, path, text) {
  let expectedRevision = null
  try {
    expectedRevision = (await adapter.getMetadata(path)).revision
  } catch {
    expectedRevision = null
  }
  return adapter.writeTextIfRevision(path, text, expectedRevision)
}

export class ObsidianExporter {
  constructor({ adapter, pageStore = PageStore, formatterClass = ObsidianFormatter } = {}) {
    if (!adapter) throw new Error('ObsidianExporter requires a storage adapter')
    this.adapter = adapter
    this.pageStore = pageStore
    this.formatterClass = formatterClass
  }

  async export() {
    const pages = await this.pageStore.listPages(this.adapter)
    const formatter = new this.formatterClass({ pages })
    const files = []

    for (const page of pages) {
      const relativePath = formatter.exportPathForPage(page)
      const path = `${WikiPaths.obsidianExportRoot}/${relativePath}`
      await writeText(this.adapter, path, formatter.formatPage(page))
      files.push(path)
    }

    const indexFiles = this.buildIndexes(pages, formatter)
    for (const [relativePath, content] of Object.entries(indexFiles)) {
      const path = `${WikiPaths.obsidianExportRoot}/${relativePath}`
      await writeText(this.adapter, path, content)
      files.push(path)
    }

    const readmePath = `${WikiPaths.obsidianExportRoot}/README.md`
    await writeText(this.adapter, readmePath, this.readme())
    files.push(readmePath)

    const warningPath = `${WikiPaths.obsidianExportRoot}/EDIT_THIS_FILE_AND_ITS_OVERWRITTEN.md`
    await writeText(this.adapter, warningPath, '# Read-only export\n\nThis Obsidian mirror is regenerated by ScholarLib. Edits here are overwritten.\n')
    files.push(warningPath)

    await this.deleteStaleFiles(files)
    const manifest = { generated_at: new Date().toISOString(), files: files.sort(), page_count: pages.length }
    await writeJSONWithRevision(this.adapter, WikiPaths.obsidianExportManifest, manifest)
    return manifest
  }

  buildIndexes(pages, formatter) {
    const byType = {}
    for (const page of pages) {
      const type = page.frontmatter?.type || 'paper'
      byType[type] ||= []
      byType[type].push(page)
    }

    const files = {
      'index.md': [
        '# ScholarLib Wiki Export',
        '',
        'This is a generated, read-only Obsidian mirror.',
        '',
        ...Object.keys(byType).sort().map(type => `- [[${type}-index|${displayType(type)}]] (${byType[type].length})`),
        '',
      ].join('\n'),
    }

    for (const [type, typePages] of Object.entries(byType)) {
      const lines = [`# ${displayType(type)} index`, '']
      for (const page of typePages.sort((a, b) => (a.frontmatter?.title || a.id).localeCompare(b.frontmatter?.title || b.id))) {
        const handle = formatter.exportPathForPage(page).split('/').pop().replace(/\.md$/, '')
        lines.push(`- [[${handle}|${page.frontmatter?.title || page.id}]]`)
      }
      files[`${type}-index.md`] = `${lines.join('\n')}\n`
    }
    return files
  }

  async deleteStaleFiles(currentFiles) {
    const previous = await readJSONOrNull(this.adapter, WikiPaths.obsidianExportManifest)
    const current = new Set([...currentFiles, WikiPaths.obsidianExportManifest])
    for (const path of previous?.files || []) {
      if (!current.has(path)) {
        try { await this.adapter.deleteFile(path) } catch { /* stale already gone */ }
      }
    }
  }

  readme() {
    return `# ScholarLib Obsidian Export

This folder is a generated read-only mirror of the canonical ScholarLib wiki at \`_wiki/\`.

Do not edit files in this export. Regeneration overwrites this directory and discards local edits.

Recommended Obsidian plugins:
- Dataview
- Graph Analysis

If links look stale or broken, regenerate the export from ScholarLib settings.
`
  }
}
